// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAiUeuP3kUqXmkxZzUVzxBGi1FaSRKh57k',
    appId: '1:265856517704:web:35a591811eb4515bc27a7d',
    messagingSenderId: '265856517704',
    projectId: 'real-time-chat-applicati-2b6bd',
    authDomain: 'real-time-chat-applicati-2b6bd.firebaseapp.com',
    storageBucket: 'real-time-chat-applicati-2b6bd.firebasestorage.app',
    measurementId: 'G-Z4JJPYLQR8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB5X53PZxXyCuAn4qFE62uK4BKsynvLDPQ',
    appId: '1:265856517704:android:1d43188a5aeade80c27a7d',
    messagingSenderId: '265856517704',
    projectId: 'real-time-chat-applicati-2b6bd',
    storageBucket: 'real-time-chat-applicati-2b6bd.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCat4hwXZzJPucnIYe5qCYynERUmvahMjU',
    appId: '1:265856517704:ios:bf7aec28ef0fc394c27a7d',
    messagingSenderId: '265856517704',
    projectId: 'real-time-chat-applicati-2b6bd',
    storageBucket: 'real-time-chat-applicati-2b6bd.firebasestorage.app',
    iosBundleId: 'com.example.realTimeChatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCat4hwXZzJPucnIYe5qCYynERUmvahMjU',
    appId: '1:265856517704:ios:bf7aec28ef0fc394c27a7d',
    messagingSenderId: '265856517704',
    projectId: 'real-time-chat-applicati-2b6bd',
    storageBucket: 'real-time-chat-applicati-2b6bd.firebasestorage.app',
    iosBundleId: 'com.example.realTimeChatApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAiUeuP3kUqXmkxZzUVzxBGi1FaSRKh57k',
    appId: '1:265856517704:web:dd584bf438683899c27a7d',
    messagingSenderId: '265856517704',
    projectId: 'real-time-chat-applicati-2b6bd',
    authDomain: 'real-time-chat-applicati-2b6bd.firebaseapp.com',
    storageBucket: 'real-time-chat-applicati-2b6bd.firebasestorage.app',
    measurementId: 'G-95EY3T77HX',
  );

}