// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAtCEzLN-UPWJakhZQs3vX477jtTjEUa7o',
    appId: '1:35575413229:web:7be53a75c1d6c978838fe4',
    messagingSenderId: '35575413229',
    projectId: 'chat-real-time-ab69e',
    authDomain: 'chat-real-time-ab69e.firebaseapp.com',
    storageBucket: 'chat-real-time-ab69e.firebasestorage.app',
    measurementId: 'G-25W6RR0D4X',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCWL21_4nd_GIMOC2gCxGJV0bX4BEyHyn4',
    appId: '1:35575413229:android:1800ac2fd66dbb57838fe4',
    messagingSenderId: '35575413229',
    projectId: 'chat-real-time-ab69e',
    storageBucket: 'chat-real-time-ab69e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCFejgcVmLHGbpD9baGHev7ZR4DehJ888c',
    appId: '1:35575413229:ios:3b5a54c174392d31838fe4',
    messagingSenderId: '35575413229',
    projectId: 'chat-real-time-ab69e',
    storageBucket: 'chat-real-time-ab69e.firebasestorage.app',
    iosBundleId: 'com.example.realTimeChatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCFejgcVmLHGbpD9baGHev7ZR4DehJ888c',
    appId: '1:35575413229:ios:3b5a54c174392d31838fe4',
    messagingSenderId: '35575413229',
    projectId: 'chat-real-time-ab69e',
    storageBucket: 'chat-real-time-ab69e.firebasestorage.app',
    iosBundleId: 'com.example.realTimeChatApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAtCEzLN-UPWJakhZQs3vX477jtTjEUa7o',
    appId: '1:35575413229:web:fc85222db4985d6a838fe4',
    messagingSenderId: '35575413229',
    projectId: 'chat-real-time-ab69e',
    authDomain: 'chat-real-time-ab69e.firebaseapp.com',
    storageBucket: 'chat-real-time-ab69e.firebasestorage.app',
    measurementId: 'G-239MFNLCD4',
  );
}
